/**
 * Demo / sample projects. Geometry is hand-drawn; sprinklers, zones and pipes
 * are generated by the real auto-design engine so the sample reflects exactly
 * what the software produces.
 */
import { produce } from "immer";
import type { Project, ProjectMeta } from "./types";
import { createProject, makeArea, makeWaterSource, rect, uid, LINE_DEFAULTS } from "./factory";
import { autoDesignAll } from "../irrigation/autoDesign";
import type { Vec } from "../geometry/geometry";
import { stationsFor } from "../materials/takeoff";

function base(meta: Partial<ProjectMeta>): Project {
  return createProject({ designer: "Alex Rivera", company: "DeltaLine Irrigation", phone: "(951) 555-0142", email: "design@deltaline.example", ...meta });
}

export function createDemoProject(): Project {
  let p = base({
    name: "Hernandez Residence",
    client: "Maria Hernandez",
    address: "1842 Vista Grande Dr, Riverside, CA 92506",
    status: "design",
    projectType: "new-install",
    notes: "Full front and back lawn irrigation. Customer wants smart controller and minimal overspray onto driveway and patio.",
  });
  p = produce(p, (d) => {
    d.areas.push(makeArea("property", rect(0, 0, 100, 150), "Property boundary"));
    d.areas.push(makeArea("building", rect(18, 72, 62, 42), "House"));
    d.areas.push(makeArea("driveway", rect(62, 114, 18, 36), "Driveway"));
    d.areas.push(makeArea("walkway", rect(38, 114, 24, 4), "Paver walkway (4')"));
    d.areas.push(makeArea("patio", rect(34, 58, 30, 14), "Rear patio"));
    d.areas.push(makeArea("lawn", rect(4, 118, 58, 28), "Front lawn"));
    const back: Vec[] = [
      { x: 6, y: 6 },
      { x: 94, y: 6 },
      { x: 94, y: 68 },
      { x: 64, y: 68 },
      { x: 64, y: 58 },
      { x: 34, y: 58 },
      { x: 34, y: 68 },
      { x: 6, y: 68 },
    ];
    d.areas.push(makeArea("lawn", back, "Backyard lawn"));
    const bed1 = makeArea("bed", rect(18, 68, 16, 4), "Flower bed");
    bed1.plantType = "shrubs";
    d.areas.push(bed1);
    d.areas.push(makeArea("bed", rect(64, 68, 16, 4), "Flower bed (east)"));
    d.lines.push({ id: uid("line"), type: "fence", name: "Wood fence", points: [{ x: 0, y: 110 }, { x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 110 }], style: { ...LINE_DEFAULTS.fence.style }, layer: "property" });
    d.plants.push({ id: uid("tree"), type: "tree", name: "Coast live oak", position: { x: 86, y: 16 }, canopyRadius: 9, layer: "planting" });
    d.plants.push({ id: uid("tree"), type: "tree", name: "Crape myrtle", position: { x: 10, y: 140 }, canopyRadius: 5, layer: "planting" });
    for (const x of [22, 26, 30]) d.plants.push({ id: uid("shr"), type: "shrub", name: "Shrub", position: { x, y: 70 }, canopyRadius: 1.4, layer: "planting" });
    d.waterSources.push(
      makeWaterSource({ x: 82, y: 108 }, { name: "POC-1 (house main)", staticPsi: 72, meterSize: "3/4", serviceLineSize: 1, serviceLineLengthFt: 45, flowTest: { gallons: 5, seconds: 13.6 }, backflow: "pvb", backflowSize: 1, mainlineSize: 1 }),
    );
    d.equipment.push({ id: uid("eq"), type: "smart-controller", position: { x: 80.9, y: 98 }, stations: 6, layer: "electrical", label: "Smart controller (garage wall)" });
    d.equipment.push({ id: uid("eq"), type: "rain-sensor", position: { x: 80.9, y: 94 }, layer: "electrical", label: "Rain sensor" });
    d.labels.push({ id: uid("lbl"), position: { x: 36, y: 149 }, text: "VISTA GRANDE DR (STREET)", size: 2.2, rotation: 0, color: "#475569", layer: "labels" });
    d.dimensions.push({ id: uid("dim"), kind: "horizontal", a: { x: 0, y: 150 }, b: { x: 100, y: 150 }, offset: 5, layer: "measurements" });
    d.dimensions.push({ id: uid("dim"), kind: "vertical", a: { x: 100, y: 0 }, b: { x: 100, y: 150 }, offset: 5, layer: "measurements" });
    d.meta.planNotes.push("Rotors: set arcs per plan; trim radius with adjustment screw (max 25%).");
  });
  const r = autoDesignAll(p, { headClass: "rotor" }, false);
  return produce(r.project, (d) => {
    d.meta.status = "design";
  });
}

interface Spec {
  meta: Partial<ProjectMeta>;
  lot: [number, number];
  house: [number, number, number, number];
  lawns: Vec[][];
  hard: [string, Vec[]][];
  staticPsi: number;
  gpm: number;
  daysAgo: number;
}

function fromSpec(s: Spec): Project {
  let p = base(s.meta);
  p = produce(p, (d) => {
    d.areas.push(makeArea("property", rect(0, 0, s.lot[0], s.lot[1])));
    d.areas.push(makeArea("building", rect(...s.house), "House"));
    for (const [t, pts] of s.hard) d.areas.push(makeArea(t as "driveway", pts));
    s.lawns.forEach((pts, i) => d.areas.push(makeArea("lawn", pts, i === 0 ? "Front lawn" : i === 1 ? "Back lawn" : `Lawn ${i + 1}`)));
    const [hx, hy, hw] = s.house;
    d.waterSources.push(makeWaterSource({ x: hx + hw + 2, y: hy + 4 }, { staticPsi: s.staticPsi, availableGpm: s.gpm, meterSize: "1", serviceLineSize: 1 }));
    d.equipment.push({ id: uid("eq"), type: "smart-controller", position: { x: hx + hw + 0.9, y: hy + 10 }, stations: 8, layer: "electrical" });
  });
  const r = autoDesignAll(p, { headClass: "auto" });
  const t = new Date(Date.now() - s.daysAgo * 86400000).toISOString();
  return produce(r.project, (d) => {
    for (const e of d.equipment) if (e.type.includes("controller")) e.stations = stationsFor(d.zones.length);
    d.updatedAt = t;
    d.createdAt = new Date(Date.now() - (s.daysAgo + 12) * 86400000).toISOString();
  });
}

export function createSampleProjects(): Project[] {
  const smith = fromSpec({
    meta: { name: "Smith Residence", client: "John & Karen Smith", address: "412 Maple Ridge Ct, Temecula, CA 92591", status: "design", projectType: "new-install" },
    lot: [110, 150],
    house: [25, 55, 60, 45],
    lawns: [rect(6, 108, 52, 36), rect(6, 6, 98, 44), rect(88, 55, 18, 45)],
    hard: [["driveway", rect(62, 100, 20, 50)], ["walkway", rect(40, 100, 4, 8)]],
    staticPsi: 68,
    gpm: 18,
    daysAgo: 0.01,
  });
  const martinez = fromSpec({
    meta: { name: "Martinez Backyard", client: "Luis Martinez", address: "88 Sycamore Ln, Corona, CA 92882", status: "quoted", projectType: "renovation" },
    lot: [80, 120],
    house: [12, 60, 56, 40],
    lawns: [rect(6, 8, 68, 44)],
    hard: [["patio", rect(26, 50, 24, 10)]],
    staticPsi: 60,
    gpm: 14,
    daysAgo: 1,
  });
  const oak = fromSpec({
    meta: { name: "Oak View Renovation", client: "Oak View HOA", address: "2200 Oak View Pkwy, Murrieta, CA 92562", status: "installation", projectType: "renovation" },
    lot: [160, 140],
    house: [40, 50, 70, 40],
    lawns: [rect(6, 96, 150, 38), rect(6, 6, 148, 40), rect(6, 50, 30, 40), rect(116, 50, 38, 40)],
    hard: [["walkway", rect(72, 90, 6, 44)]],
    staticPsi: 75,
    gpm: 24,
    daysAgo: 2,
  });
  return [smith, martinez, oak];
}
