-- ════════════════════════════════════════════════════════════════════════
-- DeltaLine Irrigation CRM — core relational schema (PostgreSQL 15 / Supabase)
--
-- Multi-tenant: every business row carries org_id → organizations.id and is
-- protected by row-level security (see 0002_security.sql). Primary keys are
-- text ids generated by the app (prefix_random) so offline-created records
-- keep their ids when synced; uuid ids also fit.
--
-- Conventions
--   money        numeric(12,2)   dollars
--   quantities   numeric(12,3)
--   timestamps   timestamptz     (created_at / updated_at maintained by trigger)
--   soft enums   text + CHECK    (easy to extend without enum migrations)
-- ════════════════════════════════════════════════════════════════════════

create extension if not exists pg_trgm;

-- ───────────────────────── Tenancy & users ─────────────────────────

create table organizations (
  id            text primary key,
  name          text not null,
  legal_name    text,
  phone         text,
  email         text,
  website       text,
  street text, city text, state text, zip text,
  license       text,
  logo_url      text,
  settings      jsonb not null default '{}'::jsonb,   -- CrmSettings (tax, markup, terms, permissions, numbering…)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table employees (
  id              text primary key,
  org_id          text not null references organizations(id) on delete cascade,
  first_name      text not null,
  last_name       text not null,
  role            text not null check (role in ('owner','admin','estimator','technician','crew_lead','helper','office')),
  phone           text,
  email           text,
  color           text not null default '#0f6490',
  pay_type        text not null default 'hourly' check (pay_type in ('hourly','salary')),
  pay_rate        numeric(10,2) not null default 0,
  commission_pct  numeric(5,2) not null default 0,
  certifications  jsonb not null default '[]'::jsonb,
  truck_id        text,                                    -- fk added after trucks
  hire_date       date,
  active          boolean not null default true,
  work_days       smallint[] not null default '{1,2,3,4,5}',
  shift_start     time default '07:00',
  shift_end       time default '15:30',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- App users map Supabase auth identities to an org + employee + role.
create table users (
  id            uuid primary key references auth.users(id) on delete cascade,
  org_id        text not null references organizations(id) on delete cascade,
  employee_id   text references employees(id) on delete set null,
  email         text not null,
  role          text not null check (role in ('owner','admin','estimator','technician','crew_lead','helper','office','customer')),
  customer_id   text,                                      -- portal users
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table trucks (
  id            text primary key,
  org_id        text not null references organizations(id) on delete cascade,
  name          text not null,
  vehicle       text,
  plate         text,
  employee_id   text references employees(id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
alter table employees add constraint employees_truck_fk foreign key (truck_id) references trucks(id) on delete set null;

-- ───────────────────────── Marketing ─────────────────────────

create table marketing_sources (            -- campaigns
  id            text primary key,
  org_id        text not null references organizations(id) on delete cascade,
  name          text not null,
  source        text not null check (source in ('google','google_ads','facebook','instagram','yelp','referral','door_hanger','yard_sign','website','repeat','other','seo')),
  start_date    date not null,
  end_date      date,
  spend         numeric(12,2) not null default 0,
  notes         text,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ───────────────────────── Customers & properties ─────────────────────────

create table customers (
  id                text primary key,
  org_id            text not null references organizations(id) on delete cascade,
  first_name        text not null,
  last_name         text not null,
  company           text,
  type              text not null default 'residential' check (type in ('residential','commercial','hoa','property_manager','municipal')),
  phone             text,
  alt_phone         text,
  email             text,
  billing_street text, billing_city text, billing_state text, billing_zip text,
  lead_source       text not null default 'other',
  campaign_id       text references marketing_sources(id) on delete set null,
  tags              text[] not null default '{}',
  notes             text,
  preferred_contact text not null default 'call',
  portal_enabled    boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
alter table users add constraint users_customer_fk foreign key (customer_id) references customers(id) on delete set null;

create table properties (
  id                   text primary key,
  org_id               text not null references organizations(id) on delete cascade,
  customer_id          text not null references customers(id) on delete cascade,
  name                 text not null,
  street text not null, city text, state text, zip text,
  lat                  double precision,
  lng                  double precision,
  photo_url            text,
  lot_notes            text,
  lot_size_sqft        integer,
  gate_code            text,
  access_notes         text,
  pets                 text,
  landscape_notes      text,
  water_source         text not null default 'municipal' check (water_source in ('municipal','well','reclaimed','pump','other')),
  meter_size           text,
  service_line_size    text,
  main_line_size       text,
  main_line_material   text,
  static_psi           numeric(6,1),
  dynamic_psi          numeric(6,1),
  available_gpm        numeric(6,1),
  backflow_type        text not null default 'none' check (backflow_type in ('none','pvb','rp','dcva','avb')),
  backflow_make        text,
  backflow_size        text,
  backflow_location    text,
  backflow_serial      text,
  backflow_last_test   date,
  controller_location  text,
  valve_locations      text,
  system_installed_year smallint,
  recommended_upgrades text[] not null default '{}',
  design_project_id    text,                 -- Design Studio engineering plan
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index properties_customer_idx on properties(customer_id);

-- ───────────────────────── Irrigation systems ─────────────────────────

create table irrigation_systems (
  id               text primary key,
  org_id           text not null references organizations(id) on delete cascade,
  property_id      text not null references properties(id) on delete cascade,
  name             text not null default 'Main system',
  installed_year   smallint,
  installed_by     text,
  last_audit_date  date,
  notes            text,
  map_background   jsonb,                    -- {url, kind, opacity}
  map_width        integer not null default 1000,
  map_height       integer not null default 700,
  map_ft_per_unit  numeric(8,4) not null default 0.15,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index irrigation_systems_property_idx on irrigation_systems(property_id);

create table controllers (
  id             text primary key,
  org_id         text not null references organizations(id) on delete cascade,
  system_id      text not null references irrigation_systems(id) on delete cascade,
  manufacturer   text not null,
  model          text not null,
  stations       smallint not null default 6,
  location       text,
  smart          boolean not null default false,
  wifi           boolean not null default false,
  rain_sensor    boolean not null default false,
  installed_date date,
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index controllers_system_idx on controllers(system_id);

create table zones (
  id                 text primary key,
  org_id             text not null references organizations(id) on delete cascade,
  system_id          text not null references irrigation_systems(id) on delete cascade,
  number             smallint not null,
  name               text not null,
  area               text not null default 'lawn' check (area in ('lawn','drip','beds','trees','slope','groundcover','mixed')),
  valve_type         text, valve_size text, valve_location text,
  pipe_size          text, pipe_material text,
  flow_gpm           numeric(6,2),
  operating_psi      numeric(6,1),
  sprinkler_type     text, nozzle_type text,
  head_count         smallint not null default 0,
  head_spacing_ft    numeric(5,1),
  manufacturer       text, model text,
  drip_emitter_type  text, drip_line_type text,
  controller_station smallint,
  statuses           text[] not null default '{working}',   -- working, needs_adjustment, leaking, broken, clogged, poor_coverage, low_pressure, high_pressure, valve_issue, wiring_issue, controller_issue
  problems           text,
  notes              text,
  installed_date     date,
  last_repair_date   date,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (system_id, number)
);

-- Every item drawn on a system map. valves / sprinklers hold type-specific detail
-- (class-table inheritance keyed by component id).
create table components (
  id             text primary key,
  org_id         text not null references organizations(id) on delete cascade,
  system_id      text not null references irrigation_systems(id) on delete cascade,
  zone_id        text references zones(id) on delete set null,
  type           text not null check (type in ('rotor','spray','mp_rotator','drip_zone','bubbler','valve','valve_box','controller','backflow','meter','shutoff','main_line','lateral','drip_line','sleeve','wire','tree','flower_bed','lawn','structure','hardscape','note')),
  label          text,
  x              numeric(10,2) not null default 0,
  y              numeric(10,2) not null default 0,
  points         jsonb,                      -- [{x,y}] for lines / polygons
  rotation       numeric(6,2),
  size           text,
  manufacturer   text,
  model          text,
  installed_date date,
  condition      text not null default 'unknown' check (condition in ('good','fair','poor','failed','unknown')),
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index components_system_idx on components(system_id);
create index components_model_trgm on components using gin ((coalesce(manufacturer,'') || ' ' || coalesce(model,'')) gin_trgm_ops);

create table valves (
  component_id  text primary key references components(id) on delete cascade,
  valve_type    text not null default 'anti-siphon' check (valve_type in ('anti-siphon','inline','master','drip','isolation')),
  flow_control  boolean not null default false,
  solenoid      text,
  depth_in      numeric(5,1)
);

create table sprinklers (
  component_id  text primary key references components(id) on delete cascade,
  arc_deg       numeric(5,1),
  radius_ft     numeric(5,1),
  nozzle        text,
  pop_up_in     numeric(4,1),
  flow_gpm      numeric(6,3)
);

-- ───────────────────────── Leads ─────────────────────────

create table leads (
  id                text primary key,
  org_id            text not null references organizations(id) on delete cascade,
  first_name        text not null,
  last_name         text,
  phone             text,
  email             text,
  street text, city text, state text, zip text,
  service_type      text not null,
  description       text,
  source            text not null default 'other',
  campaign_id       text references marketing_sources(id) on delete set null,
  stage             text not null default 'new' check (stage in ('new','contacted','site_visit','estimate_scheduled','estimate_sent','follow_up','approved','lost')),
  urgency           text not null default 'normal' check (urgency in ('low','normal','high','emergency')),
  estimated_value   numeric(12,2) not null default 0,
  assigned_to       text references employees(id) on delete set null,
  last_contact_at   timestamptz,
  next_follow_up_at timestamptz,
  preferred_dates   text,
  notes             text,
  lost_reason       text,
  customer_id       text references customers(id) on delete set null,
  property_id       text references properties(id) on delete set null,
  sort              integer not null default 0,
  converted_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index leads_stage_idx on leads(org_id, stage);

-- ───────────────────────── Price book & inventory ─────────────────────────

create table vendors (
  id              text primary key,
  org_id          text not null references organizations(id) on delete cascade,
  name            text not null,
  contact_name    text, phone text, email text, website text,
  account_number  text,
  address         text,
  categories      text[] not null default '{}',
  payment_terms   text,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table inventory_items (               -- master price book
  id                   text primary key,
  org_id               text not null references organizations(id) on delete cascade,
  name                 text not null,
  sku                  text,
  category             text not null check (category in ('sprinklers','rotors','nozzles','valves','pvc','fittings','drip','controllers','wire','backflow','labor','equipment','misc')),
  manufacturer         text,
  description          text,
  unit                 text not null default 'ea',
  cost                 numeric(12,4) not null default 0,
  pricing_rule         text not null default 'markup' check (pricing_rule in ('multiplier','markup','margin','flat')),
  pricing_value        numeric(12,4) not null default 0,
  taxable              boolean not null default true,
  stocked              boolean not null default true,
  warehouse_qty        numeric(12,3) not null default 0,
  min_qty              numeric(12,3) not null default 0,
  reorder_qty          numeric(12,3) not null default 0,
  preferred_vendor_id  text references vendors(id) on delete set null,
  vendor_sku           text,
  labor_hrs_per_unit   numeric(6,3),
  active               boolean not null default true,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (org_id, sku)
);
create index inventory_items_name_trgm on inventory_items using gin (name gin_trgm_ops);

create table truck_inventory (
  id         text primary key,
  org_id     text not null references organizations(id) on delete cascade,
  truck_id   text not null references trucks(id) on delete cascade,
  item_id    text not null references inventory_items(id) on delete cascade,
  qty        numeric(12,3) not null default 0,
  min_qty    numeric(12,3) not null default 0,
  updated_at timestamptz not null default now(),
  unique (truck_id, item_id)
);

-- ───────────────────────── Estimates ─────────────────────────

create table estimates (
  id                  text primary key,
  org_id              text not null references organizations(id) on delete cascade,
  number              integer not null,
  customer_id         text not null references customers(id) on delete restrict,
  property_id         text not null references properties(id) on delete restrict,
  lead_id             text references leads(id) on delete set null,
  title               text not null,
  service_type        text not null,
  status              text not null default 'draft' check (status in ('draft','sent','viewed','approved','declined','expired')),
  selected_option_id  text,
  tax_pct             numeric(6,3) not null default 0,
  discount_type       text not null default 'amount' check (discount_type in ('pct','amount')),
  discount_value      numeric(12,2) not null default 0,
  discount_reason     text,
  trip_charge         numeric(12,2) not null default 0,
  diagnostic_fee      numeric(12,2) not null default 0,
  deposit_pct         numeric(5,2) not null default 0,
  customer_notes      text,
  internal_notes      text,
  terms               text,
  created_by          text references employees(id) on delete set null,
  valid_until         date,
  sent_at timestamptz, viewed_at timestamptz, approved_at timestamptz, declined_at timestamptz, last_follow_up_at timestamptz,
  signature           jsonb,                 -- {name, dataUrl|storage path, signedAt, ip}
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (org_id, number)
);
alter table leads add column estimate_id text references estimates(id) on delete set null;

create table estimate_options (               -- Good / Better / Best
  id           text primary key,
  estimate_id  text not null references estimates(id) on delete cascade,
  name         text not null,
  description  text,
  tier         text check (tier in ('good','better','best')),
  sort         smallint not null default 0
);

create table estimate_items (
  id           text primary key,
  estimate_id  text not null references estimates(id) on delete cascade,
  option_id    text not null references estimate_options(id) on delete cascade,
  item_id      text references inventory_items(id) on delete set null,
  kind         text not null check (kind in ('material','labor','equipment','fee','subcontract','other')),
  name         text not null,
  description  text,
  qty          numeric(12,3) not null default 1,
  unit         text not null default 'ea',
  unit_cost    numeric(12,4) not null default 0,
  unit_price   numeric(12,4) not null default 0,
  taxable      boolean not null default true,
  sort         smallint not null default 0
);
create index estimate_items_estimate_idx on estimate_items(estimate_id);

create table estimate_templates (
  id            text primary key,
  org_id        text not null references organizations(id) on delete cascade,
  name          text not null,
  service_type  text not null,
  description   text,
  options       jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ───────────────────────── Install projects ─────────────────────────

create table install_projects (
  id               text primary key,
  org_id           text not null references organizations(id) on delete cascade,
  name             text not null,
  customer_id      text not null references customers(id) on delete cascade,
  property_id      text not null references properties(id) on delete cascade,
  lead_id          text references leads(id) on delete set null,
  estimate_id      text references estimates(id) on delete set null,
  stage            text not null default 'lead',
  stage_dates      jsonb not null default '{}'::jsonb,
  design           jsonb not null default '{}'::jsonb,   -- available GPM, PSI, sizes, zone flows…
  takeoff          jsonb not null default '[]'::jsonb,   -- material takeoff lines
  permit_required  boolean not null default false,
  permit_number    text,
  notes            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- ───────────────────────── Service plans ─────────────────────────

create table service_plans (
  id                     text primary key,
  org_id                 text not null references organizations(id) on delete cascade,
  name                   text not null,
  description            text,
  price                  numeric(12,2) not null default 0,
  billing                text not null default 'per_visit' check (billing in ('per_visit','monthly','annual')),
  frequency              text not null check (frequency in ('monthly','quarterly','semiannual','annual','seasonal')),
  visits_per_year        smallint not null default 1,
  included_services      text[] not null default '{}',
  discount_pct           numeric(5,2) not null default 0,
  checklist_template_id  text,
  active                 boolean not null default true,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create table service_plan_subscriptions (
  id               text primary key,
  org_id           text not null references organizations(id) on delete cascade,
  plan_id          text not null references service_plans(id) on delete restrict,
  customer_id      text not null references customers(id) on delete cascade,
  property_id      text not null references properties(id) on delete cascade,
  start_date       date not null,
  next_visit_date  date not null,
  last_visit_date  date,
  auto_renew       boolean not null default true,
  status           text not null default 'active' check (status in ('active','paused','cancelled')),
  price_override   numeric(12,2),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index plan_subs_next_idx on service_plan_subscriptions(org_id, next_visit_date) where status = 'active';

-- ───────────────────────── Jobs ─────────────────────────

create table checklist_templates (
  id             text primary key,
  org_id         text not null references organizations(id) on delete cascade,
  name           text not null,
  service_types  text[] not null default '{}',
  items          text[] not null default '{}',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table jobs (
  id                     text primary key,
  org_id                 text not null references organizations(id) on delete cascade,
  number                 integer not null,
  customer_id            text not null references customers(id) on delete restrict,
  property_id            text not null references properties(id) on delete restrict,
  estimate_id            text references estimates(id) on delete set null,
  install_id             text references install_projects(id) on delete set null,
  plan_subscription_id   text references service_plan_subscriptions(id) on delete set null,
  title                  text not null,
  service_type           text not null,
  status                 text not null default 'unscheduled' check (status in ('unscheduled','scheduled','en_route','arrived','in_progress','waiting_parts','paused','completed','needs_follow_up','callback','cancelled')),
  priority               text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_to            text references employees(id) on delete set null,
  scheduled_start        timestamptz,
  duration_hrs           numeric(5,2) not null default 2,
  arrival_window         text,
  scope                  text,
  equipment              text,
  internal_notes         text,
  customer_notes         text,
  checklist_template_id  text references checklist_templates(id) on delete set null,
  estimated_labor_hours  numeric(6,2) not null default 0,
  est_revenue            numeric(12,2) not null default 0,
  est_material_cost      numeric(12,2) not null default 0,
  est_labor_cost         numeric(12,2) not null default 0,
  est_equipment_cost     numeric(12,2) not null default 0,
  signature              jsonb,
  follow_up              jsonb,
  callback_of_job_id     text references jobs(id) on delete set null,
  started_at             timestamptz,
  completed_at           timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (org_id, number)
);
create index jobs_schedule_idx on jobs(org_id, scheduled_start);
create index jobs_status_idx on jobs(org_id, status);
create index jobs_assigned_idx on jobs(assigned_to, scheduled_start);
alter table estimates add column job_id text references jobs(id) on delete set null;
alter table install_projects add column job_id text references jobs(id) on delete set null;
alter table estimates add column install_id text references install_projects(id) on delete set null;

create table job_crew (
  job_id       text not null references jobs(id) on delete cascade,
  employee_id  text not null references employees(id) on delete cascade,
  primary key (job_id, employee_id)
);

create table job_zones (                       -- zones / components a job touched
  job_id        text not null references jobs(id) on delete cascade,
  zone_id       text references zones(id) on delete cascade,
  component_id  text references components(id) on delete cascade,
  check (zone_id is not null or component_id is not null)
);

create table change_orders (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  job_id       text not null references jobs(id) on delete cascade,
  number       integer not null,
  title        text not null,
  description  text,
  items        jsonb not null default '[]'::jsonb,
  status       text not null default 'pending' check (status in ('pending','approved','declined')),
  signature    jsonb,
  created_by   text references employees(id) on delete set null,
  decided_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table job_items (
  id               text primary key,
  job_id           text not null references jobs(id) on delete cascade,
  item_id          text references inventory_items(id) on delete set null,
  change_order_id  text references change_orders(id) on delete set null,
  kind             text not null check (kind in ('material','labor','equipment','fee','subcontract','other')),
  name             text not null,
  description      text,
  qty              numeric(12,3) not null default 1,
  used_qty         numeric(12,3),
  unit             text not null default 'ea',
  unit_cost        numeric(12,4) not null default 0,
  unit_price       numeric(12,4) not null default 0,
  taxable          boolean not null default true,
  added_in_field   boolean not null default false,
  sort             smallint not null default 0
);
create index job_items_job_idx on job_items(job_id);

create table job_checklist_items (
  id        text primary key,
  job_id    text not null references jobs(id) on delete cascade,
  label     text not null,
  done      boolean not null default false,
  done_at   timestamptz,
  done_by   text references employees(id) on delete set null,
  sort      smallint not null default 0
);

create table job_costs (                        -- equipment rental, subs, dump fees, permits
  id       text primary key,
  job_id   text not null references jobs(id) on delete cascade,
  kind     text not null check (kind in ('equipment','subcontract','other','dump','permit')),
  label    text not null,
  amount   numeric(12,2) not null default 0
);

create table appointments (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  kind         text not null check (kind in ('estimate','site_visit','meeting','follow_up','other')),
  title        text not null,
  customer_id  text references customers(id) on delete cascade,
  property_id  text references properties(id) on delete set null,
  lead_id      text references leads(id) on delete cascade,
  starts_at    timestamptz not null,
  ends_at      timestamptz not null,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create table appointment_employees (
  appointment_id text not null references appointments(id) on delete cascade,
  employee_id    text not null references employees(id) on delete cascade,
  primary key (appointment_id, employee_id)
);

-- ───────────────────────── Billing ─────────────────────────

create table invoices (
  id              text primary key,
  org_id          text not null references organizations(id) on delete cascade,
  number          integer not null,
  customer_id     text not null references customers(id) on delete restrict,
  property_id     text references properties(id) on delete set null,
  job_id          text references jobs(id) on delete set null,
  estimate_id     text references estimates(id) on delete set null,
  kind            text not null default 'standard' check (kind in ('standard','deposit','progress','service_plan')),
  status          text not null default 'draft' check (status in ('draft','sent','viewed','partial','paid','overdue','void')),
  issue_date      date not null,
  due_date        date not null,
  tax_pct         numeric(6,3) not null default 0,
  discount_type   text not null default 'amount',
  discount_value  numeric(12,2) not null default 0,
  deposit_credit  numeric(12,2) not null default 0,
  notes           text,
  terms           text,
  sent_at timestamptz, viewed_at timestamptz, paid_at timestamptz, last_reminder_at timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (org_id, number)
);
create index invoices_status_idx on invoices(org_id, status, due_date);

create table invoice_items (
  id          text primary key,
  invoice_id  text not null references invoices(id) on delete cascade,
  item_id     text references inventory_items(id) on delete set null,
  kind        text not null,
  name        text not null,
  description text,
  qty         numeric(12,3) not null default 1,
  unit        text not null default 'ea',
  unit_cost   numeric(12,4) not null default 0,
  unit_price  numeric(12,4) not null default 0,
  taxable     boolean not null default true,
  sort        smallint not null default 0
);

create table payments (
  id            text primary key,
  org_id        text not null references organizations(id) on delete cascade,
  invoice_id    text references invoices(id) on delete set null,
  customer_id   text not null references customers(id) on delete restrict,
  amount        numeric(12,2) not null check (amount <> 0),
  method        text not null check (method in ('cash','card','ach','check','other')),
  reference     text,
  received_at   timestamptz not null default now(),
  is_deposit    boolean not null default false,
  note          text,
  processor     jsonb,                       -- {provider, chargeId, fee}
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index payments_received_idx on payments(org_id, received_at);

create table inventory_transactions (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  item_id      text not null references inventory_items(id) on delete cascade,
  truck_id     text references trucks(id) on delete set null,   -- null = warehouse
  qty          numeric(12,3) not null,
  reason       text not null check (reason in ('received','used','transfer','adjustment','returned')),
  job_id       text references jobs(id) on delete set null,
  employee_id  text references employees(id) on delete set null,
  note         text,
  at           timestamptz not null default now()
);

-- ───────────────────────── Time tracking ─────────────────────────

create table time_entries (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  employee_id  text not null references employees(id) on delete cascade,
  job_id       text references jobs(id) on delete set null,
  type         text not null check (type in ('shift','travel','job','break','shop','material_pickup')),
  starts_at    timestamptz not null,
  ends_at      timestamptz,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);
create index time_entries_job_idx on time_entries(job_id);
create index time_entries_emp_idx on time_entries(employee_id, starts_at);

-- ───────────────────────── Audits ─────────────────────────

create table audit_reports (
  id                       text primary key,
  org_id                   text not null references organizations(id) on delete cascade,
  property_id              text not null references properties(id) on delete cascade,
  system_id                text not null references irrigation_systems(id) on delete cascade,
  job_id                   text references jobs(id) on delete set null,
  technician_id            text references employees(id) on delete set null,
  date                     date not null,
  status                   text not null default 'draft' check (status in ('draft','complete')),
  static_psi numeric(6,1), dynamic_psi numeric(6,1), flow_gpm numeric(6,2),
  precip_rate              numeric(5,2),
  distribution_uniformity  numeric(4,3),
  head_spacing_ok          boolean not null default true,
  nozzle_match             boolean not null default true,
  broken_heads smallint not null default 0, leaks smallint not null default 0, overspray smallint not null default 0,
  runoff smallint not null default 0, low_heads smallint not null default 0, tilted_heads smallint not null default 0,
  pressure_problems text, valve_issues text, controller_settings text, watering_schedule text,
  minutes_per_week         integer,
  soil_type text, sun_exposure text, slope_pct numeric(5,1), plant_type text,
  irrigated_sqft           integer,
  zone_findings            jsonb not null default '[]'::jsonb,
  notes                    text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- ───────────────────────── Media ─────────────────────────
-- url = Supabase Storage path (bucket "media"); annotations are vector overlays.

create table photos (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  url          text not null,
  caption      text,
  category     text not null check (category in ('before','during','after','problem','repair','system_map')),
  entity_type  text not null,
  entity_id    text not null,
  customer_id  text references customers(id) on delete cascade,
  property_id  text references properties(id) on delete cascade,
  job_id       text references jobs(id) on delete cascade,
  taken_at     timestamptz not null default now(),
  taken_by     text references employees(id) on delete set null,
  annotations  jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now()
);
create index photos_entity_idx on photos(entity_type, entity_id);

create table documents (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  name         text not null,
  type         text not null check (type in ('contract','estimate','invoice','photo','diagram','audit','permit','backflow','manual','warranty','other')),
  url          text not null,
  mime         text,
  size         bigint,
  entity_type  text not null,
  entity_id    text not null,
  customer_id  text references customers(id) on delete cascade,
  uploaded_by  text references employees(id) on delete set null,
  notes        text,
  uploaded_at  timestamptz not null default now()
);
create index documents_entity_idx on documents(entity_type, entity_id);

-- ───────────────────────── Communication ─────────────────────────

create table message_templates (
  id         text primary key,
  org_id     text not null references organizations(id) on delete cascade,
  name       text not null,
  channel    text not null check (channel in ('sms','email')),
  subject    text,
  body       text not null,
  category   text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table automations (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  name         text not null,
  description  text,
  trigger      text not null,
  delay_days   numeric(6,2) not null default 0,
  condition    text,
  action       text not null check (action in ('send_message','create_invoice','notify','create_reminder','create_purchase_alert')),
  template_id  text references message_templates(id) on delete set null,
  enabled      boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table automation_runs (
  id             text primary key,
  org_id         text not null references organizations(id) on delete cascade,
  automation_id  text not null references automations(id) on delete cascade,
  entity_id      text not null,
  result         text,
  at             timestamptz not null default now(),
  unique (automation_id, entity_id)          -- each rule fires once per record
);

create table messages (
  id             text primary key,
  org_id         text not null references organizations(id) on delete cascade,
  customer_id    text references customers(id) on delete cascade,
  lead_id        text references leads(id) on delete cascade,
  job_id         text references jobs(id) on delete set null,
  channel        text not null check (channel in ('sms','email','call','note','portal')),
  direction      text not null check (direction in ('in','out')),
  subject        text,
  body           text not null,
  template_id    text references message_templates(id) on delete set null,
  automation_id  text references automations(id) on delete set null,
  status         text not null default 'queued',
  provider_id    text,                        -- Twilio SID / Gmail message id
  by_employee    text references employees(id) on delete set null,
  at             timestamptz not null default now()
);
create index messages_customer_idx on messages(customer_id, at desc);

create table notifications (
  id          text primary key,
  org_id      text not null references organizations(id) on delete cascade,
  user_id     uuid references users(id) on delete cascade,  -- null = everyone in org
  type        text not null,
  title       text not null,
  body        text,
  link        text,
  key         text,
  read_at     timestamptz,
  created_at  timestamptz not null default now(),
  unique (org_id, key)
);

-- ───────────────────────── Warranty & audit trail ─────────────────────────

create table warranties (
  id                   text primary key,
  org_id               text not null references organizations(id) on delete cascade,
  job_id               text references jobs(id) on delete set null,
  customer_id          text not null references customers(id) on delete cascade,
  property_id          text not null references properties(id) on delete cascade,
  component_id         text references components(id) on delete set null,
  item                 text not null,
  manufacturer         text,
  installed_date       date not null,
  labor_months         smallint not null default 12,
  manufacturer_months  smallint not null default 0,
  labor_expires        date generated always as ((installed_date + make_interval(months => labor_months))::date) stored,
  mfr_expires          date generated always as ((installed_date + make_interval(months => manufacturer_months))::date) stored,
  notes                text,
  created_at           timestamptz not null default now()
);

create table activity_logs (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  type         text not null,
  message      text not null,
  entity_type  text not null,
  entity_id    text not null,
  customer_id  text references customers(id) on delete cascade,
  job_id       text references jobs(id) on delete cascade,
  amount       numeric(12,2),
  by_employee  text references employees(id) on delete set null,
  at           timestamptz not null default now()
);
create index activity_customer_idx on activity_logs(customer_id, at desc);
create index activity_job_idx on activity_logs(job_id, at desc);
create index activity_entity_idx on activity_logs(entity_type, entity_id, at desc);

-- ───────────────────────── Integrations (prepared, optional) ─────────────────────────

create table integrations (
  id           text primary key,
  org_id       text not null references organizations(id) on delete cascade,
  provider     text not null check (provider in ('google_calendar','google_maps','quickbooks','stripe','square','twilio','gmail','google_drive','zapier','weather','manufacturer_catalog')),
  status       text not null default 'disconnected' check (status in ('disconnected','connected','error')),
  config       jsonb not null default '{}'::jsonb,     -- non-secret settings
  secret_ref   text,                                    -- Supabase Vault secret id
  last_sync_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (org_id, provider)
);

create table external_refs (                -- maps local rows to QuickBooks / Stripe / Google ids
  org_id        text not null references organizations(id) on delete cascade,
  provider      text not null,
  local_table   text not null,
  local_id      text not null,
  external_id   text not null,
  synced_at     timestamptz not null default now(),
  primary key (org_id, provider, local_table, local_id)
);

create table webhook_events (               -- inbound Stripe / Twilio / Zapier events (idempotency)
  id           text primary key,
  org_id       text references organizations(id) on delete cascade,
  provider     text not null,
  payload      jsonb not null,
  processed_at timestamptz,
  received_at  timestamptz not null default now()
);

-- ───────────────────────── updated_at trigger ─────────────────────────

create or replace function set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;

do $$
declare t text;
begin
  for t in select table_name from information_schema.columns
           where table_schema = 'public' and column_name = 'updated_at'
  loop
    execute format('create trigger %I_updated before update on %I for each row execute function set_updated_at()', t, t);
  end loop;
end $$;
